/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.apache.hc.client5.http.classic.methods.HttpGet;
import org.apache.hc.client5.http.impl.classic.CloseableHttpClient;
import org.apache.hc.client5.http.impl.classic.CloseableHttpResponse;
import org.apache.hc.client5.http.impl.classic.HttpClients;
import org.apache.hc.core5.http.ParseException;
import org.apache.hc.core5.http.io.entity.EntityUtils;

import java.io.IOException;

public class App {
    public static void main(String[] args) {
        // Create an instance of CloseableHttpClient
        try (CloseableHttpClient httpClient = HttpClients.createDefault()) {
            // Create a GET request
            HttpGet request = new HttpGet("http://localhost:10000");

            // Execute the request
            try (CloseableHttpResponse response = httpClient.execute(request)) {
                // Get the response entity
                String result = EntityUtils.toString(response.getEntity());

                // Print the response
                System.out.println("Response code: " + response.getCode());
                System.out.println("Response body: " + result);
            }
        } catch (IOException | ParseException e) {
            e.printStackTrace();
        }
    }
}
